### PR TITLE
ESLint formatting (remove unused imports, add missing semicolons, fix indentation, etc)

### LINKED ISSUE #80: Cleanup code - ESLint, remove unneeded imports, DRY, etc
1. ESLint (uncomment the lines in `.eslintignore`)
2. Remove unneeded imports
3. DRY up code
4. Parameterize postgres queries instead of using template strings ([ref](https://node-postgres.com/features/queries#parameterized-query))

### PR DESCRIPTION
**Pull request by awhlam**
Fix ESLint formatting for the following files (remove unused imports, add missing semicolons, fix indentation, etc):
- index.js
- theme.js
- header.js
- App.jsx
- friends.jsx
- friend.jsx
- events.js
- /events/events.js
- login.jsx
- register.jsx

Tested in browser locally to make sure nothing broke. Tested login and registration.
Did not touch any of the other files yet (preferences, eventDetail, eventList, homepage, server, etc).

### CODE REVIEW

File: client/src/components/events/events.js [hunk 1]
```diff
@@ -1,59 +1,56 @@
...
-  let [listStyle, setListStyle] = useState('block');
-  let {state} = useLocation();
-  let [title, setTitle] = useState('');
+  const [user] = useAuthState(auth);
+  const [events, setEvents] = useState([]);
+  const [listStyle, setListStyle] = useState('block');
+  const { state } = useLocation();
+  const [title, setTitle] = useState('');
+
+  const getEventData = (user_id) => {
```
Comment (awhlam) [inline client/src/components/events/events.js:20]: ESLint said to reorder this before the `useEffect`, since the `useEffect` calls this `getEventData` function

File: client/src/components/friend.jsx [hunk 2]
```diff
@@ -2,35 +2,26 @@ import { Flex, Button } from '@chakra-ui/react';
...
+    axios.get(`/api/events/users/${event_id}`).then((res) => {
+      res.data.forEach((user) => {
+        if (user.user_id === friend.id) {
+          setIsInvited(true);
+        }
       });
+    });
   }, [friend, event_id]);
 
-  useEffect(() => {
```
Comment (awhlam) [inline client/src/components/friend.jsx:24]: Eric confirmed that we can remove this since the friends menu isn't shown when the user is logged out

**Review by seanpwelch90 — APPROVED** [review]
